{
  try {
    terminate();
  }
 catch (  IOException e) {
    logger.error("Error terminating response",e);
  }
}
